version: "3.9"
services:
  frontend:
    restart: always
    command : npm start
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - "3000:3000"